package com.metallic.chiaki.session

import androidx.annotation.StringRes
import com.pylux.stream.R

enum class ControllerAction(@StringRes val displayNameRes: Int, @StringRes val groupRes: Int) {
    LEFT_STICK_UP(R.string.controller_action_left_stick_up, R.string.controller_group_left_stick),
    LEFT_STICK_DOWN(R.string.controller_action_left_stick_down, R.string.controller_group_left_stick),
    LEFT_STICK_LEFT(R.string.controller_action_left_stick_left, R.string.controller_group_left_stick),
    LEFT_STICK_RIGHT(R.string.controller_action_left_stick_right, R.string.controller_group_left_stick),
    L3(R.string.controller_action_l3, R.string.controller_group_left_stick),
    RIGHT_STICK_UP(R.string.controller_action_right_stick_up, R.string.controller_group_right_stick),
    RIGHT_STICK_DOWN(R.string.controller_action_right_stick_down, R.string.controller_group_right_stick),
    RIGHT_STICK_LEFT(R.string.controller_action_right_stick_left, R.string.controller_group_right_stick),
    RIGHT_STICK_RIGHT(R.string.controller_action_right_stick_right, R.string.controller_group_right_stick),
    R3(R.string.controller_action_r3, R.string.controller_group_right_stick),
    DPAD_UP(R.string.controller_action_dpad_up, R.string.controller_group_dpad),
    DPAD_DOWN(R.string.controller_action_dpad_down, R.string.controller_group_dpad),
    DPAD_LEFT(R.string.controller_action_dpad_left, R.string.controller_group_dpad),
    DPAD_RIGHT(R.string.controller_action_dpad_right, R.string.controller_group_dpad),
    L1(R.string.controller_action_l1, R.string.controller_group_shoulder_buttons),
    L2(R.string.controller_action_l2, R.string.controller_group_shoulder_buttons),
    R1(R.string.controller_action_r1, R.string.controller_group_shoulder_buttons),
    R2(R.string.controller_action_r2, R.string.controller_group_shoulder_buttons),
    CROSS(R.string.controller_action_cross, R.string.controller_group_face_buttons),
    TRIANGLE(R.string.controller_action_triangle, R.string.controller_group_face_buttons),
    SQUARE(R.string.controller_action_square, R.string.controller_group_face_buttons),
    CIRCLE(R.string.controller_action_circle, R.string.controller_group_face_buttons),
    START(R.string.controller_action_start, R.string.controller_group_menu),
    SELECT(R.string.controller_action_select, R.string.controller_group_menu),
    HOME(R.string.controller_action_home, R.string.controller_group_system),
    TOUCHPAD_CLICK(R.string.controller_action_touchpad_click, R.string.controller_group_touchpad),
    TOUCHPAD_HOLD(R.string.controller_action_touchpad_hold, R.string.controller_group_touchpad),
    TOUCHPAD_LEFT_CLICK(R.string.controller_action_touchpad_left_click, R.string.controller_group_touchpad),
    TOUCHPAD_RIGHT_CLICK(R.string.controller_action_touchpad_right_click, R.string.controller_group_touchpad),
    TOUCHPAD_SWIPE_UP(R.string.controller_action_touchpad_swipe_up, R.string.controller_group_touchpad),
    TOUCHPAD_SWIPE_DOWN(R.string.controller_action_touchpad_swipe_down, R.string.controller_group_touchpad),
    TOUCHPAD_SWIPE_LEFT(R.string.controller_action_touchpad_swipe_left, R.string.controller_group_touchpad),
    TOUCHPAD_SWIPE_RIGHT(R.string.controller_action_touchpad_swipe_right, R.string.controller_group_touchpad),
}