package com.metallic.chiaki.session

enum class ControllerAction(val displayName: String, val group: String) {
    LEFT_STICK_UP("Left Stick Up", "Left Stick"),
    LEFT_STICK_DOWN("Left Stick Down", "Left Stick"),
    LEFT_STICK_LEFT("Left Stick Left", "Left Stick"),
    LEFT_STICK_RIGHT("Left Stick Right", "Left Stick"),
    L3("L3 Click", "Left Stick"),
    RIGHT_STICK_UP("Right Stick Up", "Right Stick"),
    RIGHT_STICK_DOWN("Right Stick Down", "Right Stick"),
    RIGHT_STICK_LEFT("Right Stick Left", "Right Stick"),
    RIGHT_STICK_RIGHT("Right Stick Right", "Right Stick"),
    R3("R3 Click", "Right Stick"),
    DPAD_UP("D-Pad Up", "D-Pad"),
    DPAD_DOWN("D-Pad Down", "D-Pad"),
    DPAD_LEFT("D-Pad Left", "D-Pad"),
    DPAD_RIGHT("D-Pad Right", "D-Pad"),
    L1("L1", "Shoulder Buttons"),
    L2("L2", "Shoulder Buttons"),
    R1("R1", "Shoulder Buttons"),
    R2("R2", "Shoulder Buttons"),
    CROSS("Cross (×)", "Face Buttons"),
    TRIANGLE("Triangle (△)", "Face Buttons"),
    SQUARE("Square (□)", "Face Buttons"),
    CIRCLE("Circle (○)", "Face Buttons"),
    START("Start / Options", "Menu"),
    SELECT("Select", "Menu"),
    HOME("Home (PS Button)", "System"),
    TOUCHPAD_CLICK("Touchpad Click", "Touchpad"),
    TOUCHPAD_SWIPE_UP("Touchpad Swipe Up", "Touchpad"),
    TOUCHPAD_SWIPE_DOWN("Touchpad Swipe Down", "Touchpad"),
    TOUCHPAD_SWIPE_LEFT("Touchpad Swipe Left", "Touchpad"),
    TOUCHPAD_SWIPE_RIGHT("Touchpad Swipe Right", "Touchpad"),
}